---

- name: set timezone
  copy: content="{{ timezone }}" dest=/etc/timezone owner=root group=root mode=0644
  notify: update timezone

- include: install_utilities.yml

- name: upgrade kernel
  apt: update_cache=yes name=linux-generic-lts-vivid state=present
  when: ansible_kernel | version_compare("3.18.0", "lt")
  register: upgrade_kernel
