---

- name: gather all facts
  hosts: all 
  tasks:
    - debug: msg=ok
  tags:
    - facts

- name: setup base system behavior
  hosts: all
  roles:
   - { role: ubuntu-base, tags: ['aws-pre', 'virtualbox'] }
   - { role: kdump, tags: ['aws-pre', 'virtualbox'] }
   - { role: increase-log-retention, tags: ['aws-pre', 'virtualbox'] }

- name: setup AWS CodeDeploy
  hosts: all
  roles:
   - { role: aws-codedeploy, tags: ['aws'] }

- name: setup docker
  hosts: all
  roles:
    - { role: docker, tags: ['aws', 'virtualbox'] }
    - { role: docker-base, tags: ['aws', 'virtualbox'] }

- name: setup ntp
  hosts: all
  roles:
    - { role: ntp, tags: ['aws', 'virtualbox'] }
